global using static BotWorker.Common.Config.AppConfig;
global using Logger = BotWorker.Infrastructure.Logging.Logger;
global using BotWorker.Infrastructure.Logging;
global using static BotWorker.Core.Database.SQLConn;
global using static BotWorker.Core.Database.SqlService;
global using BotWorker.Core.Database;
global using BotWorker.Infrastructure.Utils;
global using static BotWorker.Common.LogX;
global using BotWorker.Domain.Entities;
global using BotWorker.Domain.Constants;
global using BotWorker.Core.MetaDatas;
global using BotWorker.Application.Services;
global using BotWorker.Common.Config;
global using BotWorker.Common.Extensions;
global using BotWorker.Common;
global using BotWorker.Domain.Models.Messages.BotMessages;
global using BotWorker.Domain.Interfaces;
global using BotWorker.Infrastructure.Extensions;
global using BotWorker.Application.Messaging;
global using BotWorker.Modules.Achievement;
global using BotWorker.Modules.Ranking;
global using BotWorker.Modules.Buses;
global using BotWorker.Modules.Zodiac;
global using BotWorker.Modules.Office;
global using BotWorker.Modules.PollSystem;
global using BotWorker.Modules.Punch;
global using BotWorker.Modules.Quest;
global using BotWorker.Modules.JustKidding;
global using System.Text;
global using System.Collections.Generic;
global using System.Linq;
global using System.Threading.Tasks;
global using System;
global using System.Text.RegularExpressions;
global using BotWorker.Infrastructure.Persistence.Database.Mapping;
