global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Threading;
global using System.Threading.Tasks;
global using BotWorker.Domain.Entities;
global using BotWorker.Infrastructure.Persistence.ORM;
global using BotWorker.Common.Extensions;
global using BotWorker.Application.Services;
global using BotWorker.Modules.Plugins;
global using BotWorker.Infrastructure.Utils;
global using BotWorker.Infrastructure.Caching;
global using BotWorker.Domain.Constants;
global using BotWorker.Agents.Entries;
global using BotWorker.Agents.Providers;
global using BotWorker.Services;
global using BotWorker.Domain.Models.Messages.BotMessages;
global using BotWorker.Common.Data;
global using BotWorker.Domain.Interfaces;
global using BotWorker.Modules.Games;
global using BotWorker.Modules.Office;
global using BotWorker.Infrastructure.Persistence.Database;
global using BotWorker.Infrastructure.Tools;
global using BotWorker.Modules.Games.Gift;
global using BotWorker.Infrastructure.Communication.Platforms.BotPublic;
global using BotWorker.Infrastructure.Logging;
global using static BotWorker.Common.C;
global using BotWorker.Common;
global using static BotWorker.Core.Configurations.AppConfig;
global using static BotWorker.Infrastructure.Persistence.Database.SQLConn;
